AbarroLaw.Web/Controllers/DynamicCasePostController.cs
using AbarroLaw.Web.Models.Domain;
using AbarroLaw.Web.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AbarroLaw.Web.Controllers
{
    public class DynamicCasePostController : Controller
    {
        private readonly ICaseRepository caseRepository;

        public DynamicCasePostController(ICaseRepository caseRepository)
        {
            this.caseRepository = caseRepository;
        }


        public async Task<IActionResult> CasePostAsync(string urlHandle)
        {

            var casePosts = await caseRepository.GetUrlHandle(urlHandle);
            var casePostsDetails = new CasePost();

            if (casePosts != null)
            {
                casePostsDetails = new CasePost
                {
                    Id = casePosts.Id,
                    CaseName = casePosts.CaseName,
                    Heading = casePosts.Heading,
                    Content = casePosts.Content,
                    ShortDescription = casePosts.ShortDescription,
                    FeaturedImg = casePosts.FeaturedImg,
                    FeaturedImgURL = casePosts.FeaturedImgURL,
                    UrlHandle = casePosts.UrlHandle,
                    PublishedDate = casePosts.PublishedDate,
                    Visible = casePosts.Visible,
                    Practices = casePosts.Practices

                };

                return View(casePostsDetails);
            }
            else
            {
                return View();
            }

        }
    }
}

AbarroLaw.Web/Controllers/PracticeAreaController.cs
using AbarroLaw.Web.Models.ViewModels;
using AbarroLaw.Web.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AbarroLaw.Web.Controllers
{
    public class PracticeAreaController : Controller
    {
        private readonly IPracticeRepository practiceRepository;
        private readonly ICaseRepository caseRepository;

        public PracticeAreaController(IPracticeRepository practiceRepository, ICaseRepository caseRepository)
        {
            this.practiceRepository = practiceRepository;
            this.caseRepository = caseRepository;
        }


        //Practice Area Main ----------------------------------------
        [HttpGet]
        public async Task<IActionResult> PracticeAreaView()
        {
            var allPractices = await practiceRepository.GetAllPracticesAsyncForUser();
            if (allPractices != null && allPractices.Any())
            {
                return View(allPractices);
            }
            else
            {
                return View();
            }

        }

        //Practice Area Dynamic (based on DB) -----------------------
        public async Task<IActionResult> PracticeAreaDynamic(string practiceName)
        {
            if (string.IsNullOrEmpty(practiceName))
            {
                return BadRequest("No cases related on the practice!");
            }
            else
            {
                var result = await caseRepository.GetCasePostsByPracticeNameAsync(practiceName);
                var casePosts = result.casePosts;
                var practiceImageUrl = result.practiceImg;

                var dynamicModel = new GetPracticeandCaseRequest
                {
                    PracticeName = practiceName,
                    PracticeImageUrl = practiceImageUrl,
                    CasePosts = casePosts.ToList()
                };

                return View(dynamicModel);
            }
        }


        
    }
}

AbarroLaw.Web/Views/PracticeArea/PracticeAreaDynamic.cshtml
@* @model List<AbarroLaw.Web.Models.Domain.CasePost> *@

@model AbarroLaw.Web.Models.ViewModels.GetPracticeandCaseRequest

@{

}
<style>
    body {
        overflow-x: hidden;
        font-family: Poppins;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 75vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 70vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(50%);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-size: 3.5vw;
        font-weight: bold;
    }

    .case-img {
        height: 35vh;
        /* filter: brightness(100%); */
    }

    .card {
        width: 25rem;
    }
</style>



@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <img class="bg-img" src="@Url.Content("~/" + Model.PracticeImageUrl)" />
    <h1 class="landing-title mt-4">
        @Model.PracticeName Cases
    </h1>
</div>


<div class="container d-flex flex-column align-items-center" style="height: auto;">
    <div style="letter-spacing: 0.5em;">
        <h2> @Model.PracticeName - Related Cases</h2>
    </div>
</div>


@if (Model.CasePosts != null && Model.CasePosts.Any())
{
    <div class="container">
        <div class="row row-cols-auto d-flex justify-content-center">
            <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var casePost in Model.CasePosts)
            {
                <div class="card mb-3 bg-light box-shadow mx-3">
                    @* for image *@
                    <div class="mb-2 bg-light box-shadow d-flex justify-content-center mt-2">
                        <img src="@Url.Content("~/" + casePost.FeaturedImgURL)" alt="@casePost.Heading" class="card-img mb-2 d-block img-fluid case-img" />
                    </div>

                    @* Heading and date *@
                    <h3 class="mb-1 text-uppercase">@casePost.Heading</h3>
                    <p class="mb-0">Publish Date: @casePost.PublishedDate.ToShortDateString()</p>

                    @* Practice area *@
                    <p class="mb-3">
                        @foreach (var practice in casePost.Practices)
                        {
                            <span class="badge bg-secondary me-1">@practice.PracticeName</span>
                        }
                    </p>

                    @* Summary *@
                    <p class="mb-4">@casePost.ShortDescription</p>
                    <div class="card-body mt-auto">
                        <a class="btn btn-dark float-end" asp-controller="DynamicCasePost" asp-action="CasePost" asp-route-urlHandle="@casePost.UrlHandle">
                            Read more >>
                        </a>
                    </div>
                </div>
            }
            </div>
        </div>
    </div>
}
else
{
    <p>No case posts found for the selected practice.</p>
}

AbarroLaw.Web/Views/PracticeArea/PracticeAreaView.cshtml
@model List<AbarroLaw.Web.Models.Domain.Practice>

@{
}


<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 70vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 70vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-size: 3.5vw;
        font-weight: bold;
    }

    .practice-area-main {
        font-family: Poppins;
    }

    .card-title {
        color: white;
    }

    .card-images {
        height: 22vh;
        filter: brightness(45%);
    }
</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <img class="bg-img" src="~/images/practice_bg.png" />
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-3"> PRACTICE AREA</h1>
    </div>
</div>


@* Cards for Practice Areas ------------------------------------------ *@
<div class="container d-flex flex-column align-items-center mb-5 mt-5" style="height: auto;">
    <div style="letter-spacing: 0.5em;">
        <h2>- OUR PRACTICE AREAS -</h2>
    </div>

    <div class="container mt-5">
        <div class="row row-cols-auto">

            @* Card format *@
            @* <div class="col">
                <div class="card mb-3" style="width: 18rem;">
                    <div class="position-relative">
                        <img src="~/images/practice/business_bg.png" class="card-img-top card-images">
                        <div class="position-absolute top-50 start-50 translate-middle">
                            <h5 class="card-title text-center">Card title</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Learn more >></a>
                    </div>
                </div>
            </div> *@

            @* src="@Url.Content("~/" + practice.PracticeImage)" *@

            @* For practices based on DB ----------------------------------- *@

            @if(Model != null && Model.Any())
            {
                @foreach (var practice in Model)
                {
                    @if (practice.Visible == "true")
                    {
                        <div class="col">
                            <div class="card mb-3" style="width: 18rem;">
                                <div class="position-relative mx-3 mt-2">
                                    <img src="@Url.Content("~/" + practice.PracticeImageURL)" class="card-img card-images">
                                    <div class="position-absolute top-50 start-50 translate-middle">
                                        <h4 class="card-title text-center">@practice.PracticeName</h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">@practice.PracticeDescription</p>
                                    <a class="btn btn-primary float-end" asp-controller="PracticeArea" asp-action="PracticeAreaDynamic" asp-route-practiceName="@practice.PracticeName">
                                        See Cases >>
                                    </a>
                                </div>
                            </div>
                        </div>
                    }
                    
                }


            }
            else
            {

                <h4>No practice areas at the moment.</h4>
            }
            

        </div>
    </div>
</div>