AbarroLaw.Web/Controllers/AdminCaseController.cs
using AbarroLaw.Web.Models.Domain;
using AbarroLaw.Web.Models.ViewModels;
using AbarroLaw.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AbarroLaw.Web.Controllers
{

    [Authorize(Roles = "Admin")]
    public class AdminCaseController : Controller
    {
        private readonly ICaseRepository caseRepository;
        private readonly IPracticeRepository practiceRepository;

        public AdminCaseController(ICaseRepository caseRepository, IPracticeRepository practiceRepository)
        {
            this.caseRepository = caseRepository;
            this.practiceRepository = practiceRepository;
        }

        //Add ----------------------------------------
        [HttpGet]
        public async Task<IActionResult> AddCase()
        {
            var practices = await practiceRepository.GetAllPracticeAsync();

            var model = new AddCaseRequest
            {
                Practices = practices.Select(x => new SelectListItem { Text = x.PracticeName, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitCase(AddCaseRequest addCaseRequest)
        {
            if (addCaseRequest.CaseName == null || addCaseRequest.Heading == null || addCaseRequest.ShortDescription == null || addCaseRequest.FeaturedImg == null || addCaseRequest.Content == null)
            {
                // Re-populate Practices in case of a validation error
                var practices = await practiceRepository.GetAllPracticeAsync();
                addCaseRequest.Practices = practices.Select(x => new SelectListItem { Text = x.PracticeName, Value = x.Id.ToString() });

                //For error handling and returning to AddCase without removing the existing input
                ModelState.AddModelError("", "Please fill out this form.");
                return View("AddCase", addCaseRequest); // Return to the form with validation error
            }
            else
            {
                //Mapping Practices
                var selectedPractices = new List<Practice>();

                foreach (var selectedPracticeId in addCaseRequest.SelectedPractices)
                {
                    var selectedPracticeGuid = Guid.Parse(selectedPracticeId);
                    var existingPractice = await practiceRepository.GetPracticeAsync(selectedPracticeGuid);

                    if (existingPractice != null)
                    {
                        selectedPractices.Add(existingPractice);
                    }
                }

                var UrlHandleMaker = GenerateUrlHandle(addCaseRequest.Heading);

                //Mapping input values to send to DB
                var casePost = new CasePost
                {
                    CaseName = addCaseRequest.CaseName,
                    Heading = addCaseRequest.Heading,
                    Content = addCaseRequest.Content,
                    ShortDescription = addCaseRequest.ShortDescription,
                    FeaturedImg = addCaseRequest.FeaturedImg,
                    FeaturedImgURL = addCaseRequest.FeaturedImgURL,
                    UrlHandle = UrlHandleMaker,
                    PublishedDate = addCaseRequest.PublishedDate,
                    Visible = addCaseRequest.Visible,
                    Practices = selectedPractices
                };

                if(selectedPractices.Count == 0 || UrlHandleMaker == null)
                {
                    // Re-populate Practices in case of a validation error
                    var practices = await practiceRepository.GetAllPracticeAsync();
                    addCaseRequest.Practices = practices.Select(x => new SelectListItem { Text = x.PracticeName, Value = x.Id.ToString() });

                    //For error handling and returning to AddCase without removing the existing input
                    ModelState.AddModelError("", "Please fill out this form.");
                    return View("AddCase", addCaseRequest); // Return to the form with validation error
                }
                else
                {
                    //Call repository to save to DB
                    await caseRepository.AddCaseAsync(casePost);

                    return RedirectToAction("ViewAllCase");
                }
            }
                        
        }

        private string GenerateUrlHandle(string input)
        {
            return input.Replace(" ", "-").ToLower();
        }


        //Read --------------------------------------
        public async Task<IActionResult> ViewAllCase()
        {
            var cases = await caseRepository.GetAllCaseAsync();

            return View(cases);
        }


        //Update ------------------------------------
        [HttpGet]
        public async Task<IActionResult> EditCase(Guid id)
        {
            var casePost = await caseRepository.GetCaseAsync(id);
            var practiceDomainModel = await practiceRepository.GetAllPracticeAsync();

            if (casePost != null)
            {
                var model = new EditCaseRequest
                {
                    Id = casePost.Id,
                    CaseName = casePost.CaseName,
                    Heading = casePost.Heading,
                    Content = casePost.Content,
                    ShortDescription = casePost.ShortDescription,
                    FeaturedImg = casePost.FeaturedImg,
                    FeaturedImgURL = casePost.FeaturedImgURL,
                    PublishedDate = casePost.PublishedDate,
                    
                    Visible = casePost.Visible,
                    Practices = practiceDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.PracticeName,
                        Value = x.Id.ToString()
                    }),
                    SelectedPractices = casePost.Practices.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);
            }
            else
            {
                return View(null);
            }

        }

        [HttpPost]
        public async Task<IActionResult> EditCase(EditCaseRequest editCaseRequest)
        {
            if (editCaseRequest.CaseName == null || editCaseRequest.Heading == null || editCaseRequest.ShortDescription == null || editCaseRequest.FeaturedImg == null || editCaseRequest.Content == null)
            {
                // Re-populate Practices in case of a validation error
                var practices = await practiceRepository.GetAllPracticeAsync();
                editCaseRequest.Practices = practices.Select(x => new SelectListItem { Text = x.PracticeName, Value = x.Id.ToString() });

                //For error handling and returning to AddCase without removing the existing input
                ModelState.AddModelError("", "Please fill out this form.");
                return View("EditCase", editCaseRequest); // Return to the form with validation error
            }
            else
            {
                //Mapping practices
                var selectedPractices = new List<Practice>();
                foreach (var selectedPractice in editCaseRequest.SelectedPractices)
                {
                    if (Guid.TryParse(selectedPractice, out var practice))
                    {
                        var foundPractice = await practiceRepository.GetPracticeAsync(practice);
                        if (foundPractice != null)
                        {
                            selectedPractices.Add(foundPractice);
                        }
                    }
                }

                var UrlHandleMaker = GenerateUrlHandle(editCaseRequest.Heading);

                //Assign values to edit request
                var casePostModel = new CasePost
                {
                    Id = editCaseRequest.Id,
                    CaseName = editCaseRequest.CaseName,
                    Heading = editCaseRequest.Heading,
                    Content = editCaseRequest.Content,
                    ShortDescription = editCaseRequest.ShortDescription,
                    FeaturedImg = editCaseRequest.FeaturedImg,
                    FeaturedImgURL = editCaseRequest.FeaturedImgURL,
                    UrlHandle = UrlHandleMaker,
                    PublishedDate = editCaseRequest.PublishedDate,
                    Visible = editCaseRequest.Visible,
                    Practices = selectedPractices
                };

                //casePostModel.Practices = selectedPractices;
                if (selectedPractices.Count == 0 || UrlHandleMaker == null)
                {
                    // Re-populate Practices in case of a validation error
                    var practices = await practiceRepository.GetAllPracticeAsync();
                    editCaseRequest.Practices = practices.Select(x => new SelectListItem { Text = x.PracticeName, Value = x.Id.ToString() });

                    //For error handling and returning to AddCase without removing the existing input
                    ModelState.AddModelError("", "Please choose at least one practice area.");
                    return View("EditCase", editCaseRequest); // Return to the form with validation error
                }
                else
                {
                    //Apply changes to DB
                    var updateCase = await caseRepository.UpdateCaseAsync(casePostModel);

                    if (updateCase != null)
                    {
                        return RedirectToAction("ViewAllCase");
                    }
                    else
                    {
                        return RedirectToAction("EditCase");
                    }
                }                   
            }            
        }


        //Delete -------------------------------------

AbarroLaw.Web/Views/AdminCase/AddCase.cshtml
@model AbarroLaw.Web.Models.ViewModels.AddCaseRequest


@{
    ViewBag.ShowFooter = false;
    ViewBag.ShowMessage = false;

    // For error displays
    ViewData["Title"] = "Edit Case";
}

<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 35vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 35vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        background-color: #305160;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-weight: bold;
    }

    .desc-area {
        height: 10vh;
        resize: none;
    }

    .container {
        font-family: Poppins;
    }
</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <div class="bg-img"></div>
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-5">ADMIN - Add New Case</h1>
    </div>
</div>


@* Contents need to fill out ------------------------------------------------- *@
<div class="container py-5">
    <form method="post" enctype="multipart/form-data" onsubmit="return confirm('Are you sure to ADD this new practice area?');">

        <!-- Validation Summary -->
        @* <div asp-validation-summary="All" class="text-danger"></div> *@

        @* Case Name *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter new case name:</label>
                <input type="text" class="form-control" id="caseName" asp-for="CaseName" />
                <span asp-validation-for="CaseName" class="text-danger"></span>
            </div>
        </div>

        @* Heading *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter heading:</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
                <span asp-validation-for="Heading" class="text-danger"></span>
            </div>
        </div>

        @* Short Description *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter the short description:</label>
                <textarea class="form-control col-md-8 col-sm-12 desc-area" id="shortDesc" asp-for="ShortDescription" oninput="limitTextArea(this, 200)"></textarea>
                <p id="charLimitIndicator">Remaining characters: 200</p>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
        </div>

        @* Feature Image Upload *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Featured image upload:</label>
                <div class="input-group">
                    <input type="file" class="form-control" id="featuredImgUpload">
                    <input type="hidden" id="featuredImageFileName" asp-for="FeaturedImg" />
                </div>

                <span asp-validation-for="FeaturedImg" class="text-danger"></span>
                <img src="" id="featuredImageDisplay" style="display: none; width: 20vh;" />
            </div>
        </div>

        @* Feature Image URL *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Featured upload URL:</label>
                <input type="text" class="form-control" id="featuredImgUploadURL" readonly asp-for="FeaturedImgURL" />
            </div>
        </div>

        @* Practices *@
        <div class="container row mb-3">
            <div class="form-group">
                <label class="form-label">Choose practice area:</label>
                <select class="form-select" asp-items="@Model.Practices" asp-for="SelectedPractices"></select>
                @Html.ValidationMessageFor(model => model.SelectedPractices, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Content *@
        <div class="container row mb-3 mt-0">
            <div class="form-group">
                <label class="form-label">Case Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
        </div>
                
        @* Published Date *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Published Date:</label>
                <input type="date" class="form-control" id="featuredImageURL" asp-for="PublishedDate" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
        </div>

        @* Visible Checkbox *@
        <div class="container row mb-3 mt-0">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label" for="flexCheckDefault">
                        Visible?
                    </label>
                    <input class="form-check-input" type="checkbox" id="staticCheck" asp-for="Visible">
                </div>
            </div>
        </div>

        @* Submit button *@
        <div class="container row">
            <div class="col-auto ms-auto">
                <button type="submit" class="btn btn-success" asp-controller="AdminCase" asp-action="SubmitCase">Submit</button>
            </div>
        </div>

    </form>
</div>


@section Scripts
{
    <script>
        // Initialize the Froala Editor
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images/upload-editor-image',
            events: {
                'image.uploaded': function (response) {
                    // Parse the response to get the image link
                    let responseObj = JSON.parse(response);
                    let imageUrl = responseObj.link;

                    // Log the image link to the console
                    console.log("Image uploaded successfully. Image URL:", imageUrl);
                },
                'image.inserted': function ($img, response) {
                    console.log("Image inserted:", $img[0].src);
                },
                'image.error': function (error, response) {
                    console.log("Image upload error:", error, response);
                }
            }
        });

        // for character indicator
        var charLimitIndicator = document.getElementById('charLimitIndicator');

        function limitTextArea(element, maxChars) {
            if (element.value.length > maxChars) {
                element.value = element.value.slice(0, maxChars);
                element.blur();

                charLimitIndicator.textContent = 'Maximum character limit reached.';
                charLimitIndicator.style.color = 'red';
            }
            else {
                charLimitIndicator.textContent = 'Remaining characters: ' + (maxChars - element.value.length);
                charLimitIndicator.style.color = 'black';
            }
        }


        //Image upload
        const featuredImgUploadElement = document.getElementById('featuredImgUpload');
        const featuredImageFileNameElement = document.getElementById('featuredImageFileName');
        const featuredImgUploadURLElement = document.getElementById('featuredImgUploadURL');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images/upload-image', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    //checking the link in console
                    console.log(result);

                    //Adjust the URL to remove the controller name
                    let imageUrl = result.link;
                    let currentUrl = window.location.href;
                    let controllerNameIndex = currentUrl.indexOf("AdminCase");

                    if (controllerNameIndex !== -1) {
                        //Remove controller name if it exist
                        let baseUrl = currentUrl.substring(0, controllerNameIndex);
                        imageUrl = baseUrl + imageUrl;
                    }

                    //for getting only the file name
                    const fileName = featuredImgUploadElement.files[0].name;

                    featuredImgUploadURLElement.value = result.link
                    featuredImageFileNameElement.value = fileName;
                    featuredImageDisplayElement.src = imageUrl;
                    featuredImageDisplayElement.style.display = 'block';

                });
        }
        featuredImgUploadElement.addEventListener('change', uploadFeaturedImage);


    </script>
}

AbarroLaw.Web/Views/AdminCase/EditCase.cshtml
@model AbarroLaw.Web.Models.ViewModels.EditCaseRequest


@{
    ViewBag.ShowFooter = false;
    ViewBag.ShowMessage = false;

    // For error displays
    ViewData["Title"] = "Edit Case";
}

<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 35vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 35vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        background-color: #305160;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-weight: bold;
    }

    .desc-area {
        height: 10vh;
        resize: none;
    }

    .container {
        font-family: Poppins;
    }
</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <div class="bg-img"></div>
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-5">ADMIN - Edit Case</h1>
    </div>
</div>


@* Contents need to fill out ------------------------------------------------- *@
<div class="container py-5">
    <form method="post">

        @* ID *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Case ID:</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly/>
            </div>
        </div>

        @* Case Name *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter new case name:</label>
                <input type="text" class="form-control" id="caseName" asp-for="CaseName" />
                <span asp-validation-for="CaseName" class="text-danger"></span>
            </div>
        </div>

        @* Heading *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter heading:</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
                <span asp-validation-for="Heading" class="text-danger"></span>
            </div>
        </div>

        @* Short Description *@
        <div class="container row mb-3">
            <div class="form-group">
                <textarea class="form-control col-md-8 col-sm-12 desc-area" id="shortDesc" asp-for="ShortDescription" oninput="limitTextArea(this, 200)"></textarea>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
                <p id="charLimitIndicator">Remaining characters: <span id="remainingChars">200</span></p>
            </div>
        </div>

        @* Feature Image Upload *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Featured image upload:</label>
                <div class="input-group">
                    <input type="file" class="form-control" id="featuredImgUpload">
                    <input type="hidden" id="featuredImageFileName" asp-for="FeaturedImg" />
                </div>

                <span asp-validation-for="FeaturedImg" class="text-danger"></span>

                @if (Model.FeaturedImgURL != null)
                {
                    <img src="@Url.Content("~/" + Model.FeaturedImgURL)" id="featuredImageDisplay" style="display: block; width: 20vh;" />
                }
                else
                {
                    <img src="" id="featuredImageDisplay" style="display: none; width: 20vh;" />
                }
            </div>
        </div>

        @* Feature Image URL *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Featured upload URL:</label>
                <input type="text" class="form-control" id="featuredImgUploadURL" readonly asp-for="FeaturedImgURL" />
            </div>
        </div>

        @* Practices *@
        <div class="container row mb-3">
            <div class="form-group">
                <label class="form-label">Choose practice area:</label>
                <select class="form-select" asp-items="@Model.Practices" asp-for="SelectedPractices"></select>
                @Html.ValidationMessageFor(model => model.SelectedPractices, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Content *@
        <div class="container row mb-3 mt-0">
            <div class="form-group">
                <label class="form-label">Case Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
        </div>

        @* Published Date *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Published Date:</label>
                <input type="date" class="form-control" id="featuredImageURL" asp-for="PublishedDate" />
            </div>
        </div>

        @* Visible Checkbox *@
        <div class="container row mb-3 mt-0">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label" for="flexCheckDefault">
                        Visible?
                    </label>
                    <input class="form-check-input" type="checkbox" id="staticCheck" asp-for="Visible">
                </div>
            </div>
        </div>

        @* Submit button *@
        <div class="container row">
            <div class="col-auto ms-auto">
                @* Delete Button *@
                <button type="submit" class="btn btn-danger" asp-controller="AdminCase" asp-action="DeleteCase" id="deleteForm" onclick="return confirm('Are you sure to delete this case?')">
                    Delete
                </button>

                @* Edit Button *@
                <button type="submit" class="btn btn-success" asp-controller="AdminCase" asp-action="EditCase" id="saveForm" onclick="return confirm('Save changes made to case?')">
                    Save Changes
                </button>
            </div>
        </div>

    </form>
</div>


@section Scripts
{
    <script>
        //Froala editor
        // Initialize the Froala Editor
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images/upload-editor-image',
            events: {
                'image.uploaded': function (response) {
                    // Parse the response to get the image link
                    let responseObj = JSON.parse(response);
                    let imageUrl = responseObj.link;

                    // Log the image link to the console
                    console.log("Image uploaded successfully. Image URL:", imageUrl);
                },
                'image.inserted': function ($img, response) {
                    console.log("Image inserted:", $img[0].src);
                },
                'image.error': function (error, response) {
                    console.log("Image upload error:", error, response);
                }
            }
        });

        // Character Limit on Desc
        var charLimitIndicator = document.getElementById('charLimitIndicator');

        function updateCharacterCount(element, remainingChars) {
            var currentChars = element.value.length;
            var remaining = remainingChars - currentChars;

            charLimitIndicator.textContent = 'Remaining characters: ' + remaining;
            charLimitIndicator.style.color = remaining >= 0 ? 'black' : 'red';
        }

        function limitTextArea(element, maxChars) {
            if (element.value.length > maxChars) {
                element.value = element.value.slice(0, maxChars);
                element.blur();

                charLimitIndicator.textContent = 'Maximum character limit reached.';
                charLimitIndicator.style.color = 'red';
            } else {
                updateCharacterCount(element, maxChars);
            }
        }

        document.addEventListener('DOMContentLoaded', function () {
            var textarea = document.getElementById('shortDesc');
            var maxChars = 200; // Your maximum character limit

            limitTextArea(textarea, maxChars);
        });

        //Image upload
        const featuredImgUploadElement = document.getElementById('featuredImgUpload');
        const featuredImageFileNameElement = document.getElementById('featuredImageFileName');
        const featuredImgUploadURLElement = document.getElementById('featuredImgUploadURL');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images/upload-image', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    //checking the link in console
                    console.log(result);

                    //Adjust the URL to remove the controller name
                    let imageUrl = result.link;
                    let currentUrl = window.location.href;
                    let controllerNameIndex = currentUrl.indexOf("AdminCase");

                    if (controllerNameIndex !== -1) {
                        //Remove controller name if it exist
                        let baseUrl = currentUrl.substring(0, controllerNameIndex);
                        imageUrl = baseUrl + imageUrl;
                    }

                    //for getting only the file name
                    const fileName = featuredImgUploadElement.files[0].name;

                    featuredImgUploadURLElement.value = result.link
                    featuredImageFileNameElement.value = fileName;
                    featuredImageDisplayElement.src = imageUrl;
                    featuredImageDisplayElement.style.display = 'block';

                });
        }
        featuredImgUploadElement.addEventListener('change', uploadFeaturedImage);

    </script>
}