AbarroLaw.Web/Controllers/AdminPracticeController.cs
using AbarroLaw.Web.Models.Domain;
using AbarroLaw.Web.Models.ViewModels;
using AbarroLaw.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AbarroLaw.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminPracticeController : Controller
    {
        private readonly IPracticeRepository practiceRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public AdminPracticeController(IPracticeRepository practiceRepository, IWebHostEnvironment _webHostEnvironment)
        {
            this.practiceRepository = practiceRepository;
            webHostEnvironment = _webHostEnvironment;
        }

        //Add Practice ---------------------------------------------------------------------------------------
        [HttpGet]
        public IActionResult AddPractice()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubmitPractice(AddPracticeRequest addPracticeRequest)
        {
            // Check if any required fields are null
            if (string.IsNullOrEmpty(addPracticeRequest.PracticeName) || string.IsNullOrEmpty(addPracticeRequest.PracticeDescription) || addPracticeRequest.PracticeImage == null || string.IsNullOrEmpty(addPracticeRequest.PracticeImageURL))
            {
                ModelState.AddModelError("", "Please fill out all required fields.");
                return View("AddPractice", addPracticeRequest); // Return to the same view with validation errors
            }
            else
            {
                var practiceModel = new Practice
                {
                    PracticeName = addPracticeRequest.PracticeName,
                    PracticeDescription = addPracticeRequest.PracticeDescription,
                    PracticeImage = addPracticeRequest.PracticeImage,
                    PracticeImageURL = addPracticeRequest.PracticeImageURL,
                    Visible = addPracticeRequest.Visible
                };


                await practiceRepository.AddPracticeAsync(practiceModel);

                return RedirectToAction("ViewAllPractice");

            }
        }



        //View All Practice ---------------------------------------------------------------------------------
        public async Task<IActionResult> ViewAllPractice()
        {
            var practice = await practiceRepository.GetAllPracticeAsync();
            return View(practice);

        }



        //Edit ----------------------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> EditPractice(Guid id)
        {
            var practice = await practiceRepository.GetPracticeAsync(id);

            if (practice != null)
            {
                var editPracticeRequest = new EditPracticeRequest
                {
                    Id = practice.Id,
                    PracticeName = practice.PracticeName,
                    PracticeDescription = practice.PracticeDescription,
                    PracticeImage = practice.PracticeImage,
                    PracticeImageURL = practice.PracticeImageURL,
                    Visible = practice.Visible
                };

                return View(editPracticeRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> EditPractice(EditPracticeRequest editPracticeRequest)
        {
            // Check if any required fields are null
            if (string.IsNullOrEmpty(editPracticeRequest.PracticeName) || string.IsNullOrEmpty(editPracticeRequest.PracticeDescription) || editPracticeRequest.PracticeImage == null || string.IsNullOrEmpty(editPracticeRequest.PracticeImageURL))
            {
                ModelState.AddModelError("", "Please fill out all required fields.");
                return View("EditPractice", editPracticeRequest); // Return to the same view with validation errors
            }
            else
            {
                var practice = new Practice
                {
                    Id = editPracticeRequest.Id,
                    PracticeName = editPracticeRequest.PracticeName,
                    PracticeDescription = editPracticeRequest.PracticeDescription,
                    PracticeImage = editPracticeRequest.PracticeImage,
                    PracticeImageURL = editPracticeRequest.PracticeImageURL,
                    Visible = editPracticeRequest.Visible
                };

                var updatePractice = await practiceRepository.UpdatePracticeAsync(practice);

                if (updatePractice != null)
                {
                    return RedirectToAction("ViewAllPractice");
                }
                else
                {
                    return RedirectToAction("EditPractice");
                }

            }            

        }



        //Delete --------------------------------------------------------------------------------------------
        public async Task<IActionResult> DeletePractice(EditPracticeRequest editPracticeRequest)
        {
            var deletePractice = await practiceRepository.DeletePracticeAsync(editPracticeRequest.Id);

            if (deletePractice != null)
            {
                return RedirectToAction("ViewAllPractice");
            }
            else
            {
                return RedirectToAction("EditPractice", new { id = editPracticeRequest.Id });
            }

        }
    }
}

AbarroLaw.Web/Views/AdminPractice/AddPractice.cshtml
@model AbarroLaw.Web.Models.ViewModels.AddPracticeRequest

@{
    ViewBag.ShowFooter = false;
    ViewBag.ShowMessage = false;
}

<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 35vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 35vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        background-color: #0A3232;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-weight: bold;
    }

    .desc-area {
        height: 200px;
        resize: none;
    }

    .container {
        font-family: Poppins;
    }

</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <div class="bg-img"></div>
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-5">ADMIN - Add New Practice</h1>
    </div>
</div>

@* Contents need to fill out ------------------------------------------------- *@
<div class="container py-5">
    <form method="post" asp-validation-summary="All" onsubmit="return confirm('Are you sure to ADD this new practice area?');">

        @* Practice Name *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Enter a new practice name:</label>
                <input type="text" class="form-control" id="practiceName" asp-for="PracticeName" />
                <span asp-validation-for="PracticeName" class="text-danger"></span>
            </div>
        </div>

        @* Description *@
        <div class="container row">
            <div class="form-group">
                <label>Enter the practice description:</label>
                <textarea class="form-control col-md-8 col-sm-12 desc-area" id="practiceDesc" asp-for="PracticeDescription" oninput="limitTextArea(this, 200)"></textarea>
                <span asp-validation-for="PracticeDescription" class="text-danger"></span>
                <p id="charLimitIndicator">Remaining characters: 200</p>
            </div>
        </div>

        @* Practice Image Upload *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Practice area image upload:</label>
                <div class="input-group">
                    <input type="file" class="form-control" id="practiceImgUpload">
                    <input type="hidden" id="practiceImageFileName" asp-for="PracticeImage" />
                </div>

                <span asp-validation-for="PracticeImage" class="text-danger"></span>
                <img src="" id="practiceImageDisplay" style="display: none; width: 20vh;" />
            </div>
        </div>

        @* Practice Image URL *@
        <div class="container row mb-3">
            <div class="form-group">
                <label>Image upload URL:</label>
                <input type="text" class="form-control" id="practiceImgUploadURL" readonly asp-for="PracticeImageURL" />
            </div>
        </div>

        @* Visible Checkbox *@
        <div class="container row mb-3 mt-0">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label" for="flexCheckDefault">
                        Visible?
                    </label>
                    <input class="form-check-input" type="checkbox" id="staticCheck" asp-for="Visible">
                </div>
            </div>
        </div>

        @* Submit button *@
        <div class="container row">
            <div class="col-auto ms-auto">
                <button type="submit" class="btn btn-success" asp-controller="AdminPractice" asp-action="SubmitPractice">Submit</button>
            </div>
        </div>

    </form>
</div>


<script>

    // for character indicator
    var charLimitIndicator = document.getElementById('charLimitIndicator');

    function limitTextArea(element, maxChars) {
        if (element.value.length > maxChars) {
            element.value = element.value.slice(0, maxChars);
            element.blur();

            charLimitIndicator.textContent = 'Maximum character limit reached.';
            charLimitIndicator.style.color = 'red';
        }
        else {
            charLimitIndicator.textContent = 'Remaining characters: ' + (maxChars - element.value.length);
            charLimitIndicator.style.color = 'black';
        }
    }

    //Image upload
    const practiceImgUploadElement = document.getElementById('practiceImgUpload');
    const practiceImageFileNameElement = document.getElementById('practiceImageFileName');
    const practiceImgUploadURLElement = document.getElementById('practiceImgUploadURL');
    const practiceImageDisplayElement = document.getElementById('practiceImageDisplay');

    async function uploadPracticeImage(e) {
        console.log(e.target.files[0]);

        let data = new FormData();
        data.append('file', e.target.files[0]);

        await fetch('/api/images/upload-image', {
            method: 'POST',
            headers: {
                'Accept': '*/*',
            },
            body: data
        }).then(response => response.json())
            .then(result => {
                //checking the link in console
                console.log(result);

                //Adjust the URL to remove the controller name
                let imageUrl = result.link;
                let currentUrl = window.location.href;
                let controllerNameIndex = currentUrl.indexOf("AdminPractice");

                if (controllerNameIndex !== -1) {
                    //Remove controller name if it exist
                    let baseUrl = currentUrl.substring(0, controllerNameIndex);
                    imageUrl = baseUrl + imageUrl;
                }

                //for getting only the file name
                const fileName = practiceImgUploadElement.files[0].name;

                practiceImgUploadURLElement.value = result.link
                practiceImageFileNameElement.value = fileName;
                practiceImageDisplayElement.src = imageUrl;
                practiceImageDisplayElement.style.display = 'block';


                //Direct link without removing the controller name
                // practiceImgUploadURLElement.value = result.link;
                // practiceImageDisplayElement.src = result.link;
                // practiceImageDisplayElement.style.display = 'block';
            });
    }
    practiceImgUploadElement.addEventListener('change', uploadPracticeImage);

</script>

AbarroLaw.Web/Views/AdminPractice/EditPractice.cshtml
@model AbarroLaw.Web.Models.ViewModels.EditPracticeRequest

@{
    ViewBag.ShowFooter = false;
    ViewBag.ShowMessage = false;
}

<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 35vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 35vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        background-color: #0A3232;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-weight: bold;
    }

    .desc-area {
        height: 200px;
        resize: none;
    }

    .container {
        font-family: Poppins;
    }

</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <div class="bg-img"></div>
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-5">ADMIN - Edit Practice</h1>
    </div>
</div>


<div class="container py-5">
    @* @if (Model != null)
    { *@
        <form method="post">
            @* ID *@
            <div class="container row mb-3">
                <div class="form-group">
                    <label class="form-label">ID</label>
                    <input type="text" class="form-control" id="id" asp-for="Id" readonly />
                </div>
            </div>

            @* Practice Name *@
            <div class="container row mb-3">
                <div class="form-group">
                    <label class="form-label">Enter practice name:</label>
                    <input type="text" class="form-control" id="practiceName" asp-for="PracticeName" />
                    <span asp-validation-for="PracticeName" class="text-danger"></span>
                </div>
            </div>

            @* Description *@
            <div class="container row mb-0">
                <div class="form-group">
                    <label class="form-label">Enter the practice description:</label>
                <textarea class="form-control col-md-8 col-sm-12 desc-area" id="practiceDesc" asp-for="PracticeDescription" oninput="limitTextArea(this, 200)"></textarea>
                <span asp-validation-for="PracticeDescription" class="text-danger"></span>
                    <p id="charLimitIndicator">Remaining characters: <span id="remainingChars">200</span></p>
                </div>
            </div>

            @* Practice Image Upload *@
            <div class="container row mb-3">
                <div class="form-group">
                    <label>Practice area image upload:</label>
                    <div class="input-group">
                        <input type="file" class="form-control" id="practiceImgUpload">
                        <input type="hidden" id="practiceImageFileName" asp-for="PracticeImage" />
                    </div>

                    <span asp-validation-for="PracticeImage" class="text-danger"></span>
                    @if (Model.PracticeImageURL != null)
                    {
                        <img src="@Url.Content("~/" + Model.PracticeImageURL)" id="practiceImageDisplay" style="display: block; width: 20vh;" />
                    }
                    else
                    {
                        <img src="" id="practiceImageDisplay" style="display: none; width: 20vh;" />
                    }
                </div>
            </div>

            @* Practice Image URL *@
            <div class="container row mb-3">
                <div class="form-group">
                    <label>Image upload URL:</label>
                    <input type="text" class="form-control" id="practiceImgUploadURL" readonly asp-for="PracticeImageURL" />
                </div>
            </div>

            @* Visible Checkbox *@
            <div class="container row mb-3">
                <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label" for="flexCheckDefault">
                            Visible?
                        </label>
                        <input class="form-check-input" type="checkbox" id="staticCheck" asp-for="Visible">
                    </div>
                </div>
            </div>

            @* Buttons *@
            <div class="container row">
                <div class="col-auto ms-auto">
                    @* Delete Button *@
                    <button type="submit" class="btn btn-danger" asp-controller="AdminPractice" asp-action="DeletePractice" id="deleteForm" onclick="return confirm('Are you sure to delete practice?')">
                        Delete
                    </button>

                    @* Edit Button *@
                    <button type="submit" class="btn btn-success" asp-controller="AdminPractice" asp-action="EditPractice" id="saveForm" onclick="return confirm('Save changes made to practice?')">
                        Save Changes
                    </button>

                </div>
            </div>

        </form>
    @* }
    else
    {
        <h3>Practice ID does not exist!</h3>
    } *@

</div>


<script>

    // Character Limit on Desc
    var charLimitIndicator = document.getElementById('charLimitIndicator');

    function updateCharacterCount(element, remainingChars) {
        var currentChars = element.value.length;
        var remaining = remainingChars - currentChars;

        charLimitIndicator.textContent = 'Remaining characters: ' + remaining;
        charLimitIndicator.style.color = remaining >= 0 ? 'black' : 'red';
    }

    function limitTextArea(element, maxChars) {
        if (element.value.length > maxChars) {
            element.value = element.value.slice(0, maxChars);
            element.blur();

            charLimitIndicator.textContent = 'Maximum character limit reached.';
            charLimitIndicator.style.color = 'red';
        } else {
            updateCharacterCount(element, maxChars);
        }
    }

    document.addEventListener('DOMContentLoaded', function () {
        var textarea = document.getElementById('practiceDesc');
        var maxChars = 200; // Your maximum character limit

        limitTextArea(textarea, maxChars);
    });


    //Image upload
    const practiceImgUploadElement = document.getElementById('practiceImgUpload');
    const practiceImageFileNameElement = document.getElementById('practiceImageFileName');
    const practiceImgUploadURLElement = document.getElementById('practiceImgUploadURL');
    const practiceImageDisplayElement = document.getElementById('practiceImageDisplay');

    async function uploadPracticeImage(e) {
        console.log(e.target.files[0]);

        let data = new FormData();
        data.append('file', e.target.files[0]);

        await fetch('/api/images/upload-image', {
            method: 'POST',
            headers: {
                'Accept': '*/*',
            },
            body: data
        }).then(response => response.json())
            .then(result => {
                //checking the link in console
                console.log(result);

                //Adjust the URL to remove the controller name
                let imageUrl = result.link;
                let currentUrl = window.location.href;
                let controllerNameIndex = currentUrl.indexOf("AdminPractice");

                if (controllerNameIndex !== -1) {
                    //Remove controller name if it exist
                    let baseUrl = currentUrl.substring(0, controllerNameIndex);
                    imageUrl = baseUrl + imageUrl;
                }

                //for getting only the file name
                const fileName = practiceImgUploadElement.files[0].name;

                practiceImgUploadURLElement.value = result.link
                practiceImageFileNameElement.value = fileName;
                practiceImageDisplayElement.src = imageUrl;
                practiceImageDisplayElement.style.display = 'block';


                //Direct link without removing the controller name
                // practiceImgUploadURLElement.value = result.link;
                // practiceImageDisplayElement.src = result.link;
                // practiceImageDisplayElement.style.display = 'block';
            });
    }
    practiceImgUploadElement.addEventListener('change', uploadPracticeImage);

</script>

AbarroLaw.Web/Views/AdminPractice/ViewAllPractice.cshtml
@model List<AbarroLaw.Web.Models.Domain.Practice>


@{
    ViewBag.ShowFooter = false;
    ViewBag.ShowMessage = false;
}

<style>
    body {
        overflow-x: hidden;
    }

    .flex-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 35vh; /* Adjust as necessary */
        text-align: center;
    }

    .bg-img {
        height: 35vh;
        width: 100vw;
        object-fit: cover;
        filter: brightness(0.7);
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        background-color: #0A3232;
    }

    .landing-title {
        font-family: Poppins;
        color: white;
        letter-spacing: 0.2em;
        line-height: 1.5em;
        text-align: center;
        font-weight: bold;
    }

    .auto-width {
        width: auto;
        white-space: nowrap;
    }

    /* th, td {
        font-family: Poppins;
    } */

</style>


@* Landing ------------------------------------------------------------------- *@
<div class="flex-container mt-0 pt-0">
    <div class="bg-img"></div>
    <div class="container d-flex flex-column align-items-center content-wrapper">
        <h1 class="landing-title mt-5 pt-5">ADMIN - View All Practice</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th class="auto-width">ID</th>
                    <th class="auto-width">Practice Name</th>
                    <th class="auto-width">Description</th>
                    <th class="auto-width">Visible</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var practice in Model)
                {
                    <tr>
                        <td>@practice.Id</td>
                        <td>@practice.PracticeName</td>
                        <td>@practice.PracticeDescription</td>
                        <td>@practice.Visible</td>
                        <td>
                            <button class="btn btn-primary">
                                <a asp-controller="AdminPractice" asp-action="EditPractice" asp-route-id="@practice.Id" style="color: white;">
                                    Edit
                                </a>
                            </button>
                            
                        </td>
                    </tr>
                }
                
            </tbody>
        </table>
    }
    else
    {
        <h3>No other practice areas!</h3>
    }
    
</div>